# ---------------- #
#   Main Configs   #
# ---------------- #
baseurl:
url: https://bingxin70aa.github.io/
date_format: "ordinal"
title: bing xin
subtitle: "不断尝试，永不停歇"
description: "冰昕的个人博客"
keywords: 冰昕, bingxin, hou bingxin
timezone: Asia/Guangzhou
encoding: "utf-8"
side_bar_repo_limit: 5

# ---------------- #
#      Author      #
# ---------------- #
author: Bing xin
github_username: bingxin70aa
location: Shenzhen, China
email: 424458106@qq.com

# ---------------- #
#    Navigation    #
# ---------------- #
navs:
  -
    href: /
    label: 首页

  -
    href: /posts/
    label: 笔记

  -
    href: /infovis/
    label: 信息可视化作品集

  -
    href: /porfolio/
    label: 网页设计与制作作品集

  -
    href: /about/
    label: 关于

# ---------------- #
#       RSS        #
# ---------------- #
subscribe_rss: /feed.xml

# ---------------- #
#      Jekyll      #
# ---------------- #
markdown: kramdown
kramdown:
    input: GFM
highlighter: rouge
paginate: 8
lsi: false
quiet: false
excerpt_separator: "\n\n"
permalink: /:year/:month/:day/:title/
gems:
    - jekyll-github-metadata
    - rouge
#     - jekyll-html-pipeline
    - jekyll-paginate
    - jekyll-sitemap
    - jekyll-feed
    - jemoji
#     - jekyll-mentions
collections:
    wiki:
        output: true
        permalink: /wiki/:path/

repository: bingxin70aa/bingxin70aa.github.io

# ---------------- #
#      Comments    #
# ---------------- #
# support provider: disqus, gitment, gitalk
comments_provider: gitalk
# !!!重要!!! 请修改下面这些信息为你自己申请的
# !!!Important!!! Please modify infos below to yours
# https://disqus.com
disqus:
    username: 
# https://imsun.net/posts/gitment-introduction/
gitment:
    owner: mzlogin
    repo: blog-comments
    oauth:
        client_id: d2e1cbbd298958076462
        client_secret: b42a4178e5fd4a7cf63189ef4b1453b05c375709
# https://github.com/gitalk/gitalk#install
gitalk:
    owner: bingxin70aaa
    repo: blog-comments
    clientID: 2015bfae6c3cdde60f80
    clientSecret: 939ce305ab24e5816fdc1af927e3e0886804cbd1
# 在使用其它评论组件时可点击显示 Disqus
lazy_load_disqus : false

# ---------------- #
#    Analytics     #
# ---------------- #
google:
    analytics_id: UA-80669434-1
